### Install repository to allows IPython to use Google Drive for file management

In [1]:
#git clone git://github.com/jupyter/jupyter-drive.git
#pip install -e jupyter-drive

### To install the notebook extension and activate your configuration with Google Drive

In [2]:
#python -m jupyterdrive

In [3]:
pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib

  Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl (18 kB)
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.19.6
    Uninstalling protobuf-3.19.6:
      Successfully uninstalled protobuf-3.19.6
  Attempting uninstall: google-auth-oauthlib
    Found existing installation: google-auth-oauthlib 0.4.6
    Uninstalling google-auth-oauthlib-0.4.6:
      Successfully uninstalled google-auth-oauthlib-0.4.6
  Attempting uninstall: google-api-python-client
    Found existing installation: google-api-python-client 2.80.0
    Uninstalling google-api-python-client-2.80.0:
      Successfully uninstalled google-api-python-client-2.80.0
Note: you may need to restart the kernel to use updated packages.


ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.9.1 requires protobuf<3.20,>=3.9.2, but you have protobuf 4.22.1 which is incompatible.
tensorboard 2.9.1 requires google-auth-oauthlib<0.5,>=0.4.1, but you have google-auth-oauthlib 1.0.0 which is incompatible.
tensorboard 2.9.1 requires protobuf<3.20,>=3.9.2, but you have protobuf 4.22.1 which is incompatible.
streamlit 1.19.0 requires protobuf<4,>=3.12, but you have protobuf 4.22.1 which is incompatible.
label-studio 1.7.1 requires google-auth==2.11.0, but you have google-auth 2.16.2 which is incompatible.
google-cloud-logging 2.7.2 requires protobuf<4.0.0dev, but you have protobuf 4.22.1 which is incompatible.


In [4]:
from google.colab import drive
drive.mount('/content/drive')

ModuleNotFoundError: No module named 'google.colab'

In [ ]:
DataFolder = "/content/drive/MyDrive/SDAAI/Capstone-Project"

In [1]:
pip install ultralyticsplus

Note: you may need to restart the kernel to use updated packages.


In [2]:
import torch
import cv2
# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s') 

Using cache found in C:\Users\Admin/.cache\torch\hub\ultralytics_yolov5_master
requirements: YOLOv5 requirements "gitpython>=3.1.30" "setuptools>=65.5.1" not found, attempting AutoUpdate...
  Using cached GitPython-3.1.31-py3-none-any.whl (184 kB)
     ---------------------------------------- 1.1/1.1 MB 9.9 MB/s eta 0:00:00
  Using cached gitdb-4.0.10-py3-none-any.whl (62 kB)
  Using cached smmap-5.0.0-py3-none-any.whl (24 kB)
  Attempting uninstall: setuptools
    Found existing installation: setuptools 61.2.0
    Uninstalling setuptools-61.2.0:
      Successfully uninstalled setuptools-61.2.0

requirements: 2 packages updated per C:\Users\Admin\.cache\torch\hub\ultralytics_yolov5_master\requirements.txt
requirements:  Restart runtime or rerun command for updates to take effect

YOLOv5  2023-4-5 Python-3.8.13 torch-2.0.0+cpu CPU

Fusing layers... 
YOLOv5s summary: 213 layers, 7225885 parameters, 0 gradients
Adding AutoShape... 


In [ ]:
#image_path = DataFolder+"/Safety Hat/Images/hard_hat_workers0.png" # or file, Path, PIL, OpenCV, numpy, list
image_path = DataFolder+"/Safety-Hat/Images/Helmet-Example01.jpg"

# Inference
results = model(image_path) 

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.

In [ ]:
results.show()
print(results.pandas().xyxy[0])

for i in range(len(results.pandas().xyxy[0].name)):
    print("Object",i,results.pandas().xyxy[0].name[i])

In [6]:
from ultralyticsplus import YOLO, render_result

# load model
model = YOLO('keremberke/yolov8m-hard-hat-detection')

# set model parameters
model.overrides['conf'] = 0.25  # NMS confidence threshold
model.overrides['iou'] = 0.45  # NMS IoU threshold
model.overrides['agnostic_nms'] = False  # NMS class-agnostic
model.overrides['max_det'] = 1000  # maximum number of detections per image

# set image
#image = 'https://github.com/RP-SDAAI/Capstone-Project/blob/72573878f2546c1c2984c3e1006ef8e7c72672ec/Helmet-Example01.jpg'

#image = 'https://github.com/ultralytics/yolov5/raw/master/data/images/zidane.jpg'

# perform inference
results = model.predict(image_path)

# observe results
print(results[0].boxes)
render = render_result(model=model, image=image_path, result=results[0])
render.show()

C:\Users\Admin\anaconda3\lib\site-packages\huggingface_hub\file_download.py:133: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Admin\.cache\huggingface\hub. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


NameError: name 'image_path' is not defined

## Camera Capture  
### Using a webcam to capture images for processing on the runtime.

In [ ]:
from IPython.display import display, Javascript
from google.colab.output import eval_js
from base64 import b64decode

def take_photo(filename='photo.jpg', quality=0.8):
  js = Javascript('''
    async function takePhoto(quality) {
      const div = document.createElement('div');
      const capture = document.createElement('button');
      capture.textContent = 'Capture';
      div.appendChild(capture);

      const video = document.createElement('video');
      video.style.display = 'block';
      const stream = await navigator.mediaDevices.getUserMedia({video: true});

      document.body.appendChild(div);
      div.appendChild(video);
      video.srcObject = stream;
      await video.play();

      // Resize the output to fit the video element.
      google.colab.output.setIframeHeight(document.documentElement.scrollHeight, true);

      // Wait for Capture to be clicked.
      await new Promise((resolve) => capture.onclick = resolve);

      const canvas = document.createElement('canvas');
      canvas.width = video.videoWidth;
      canvas.height = video.videoHeight;
      canvas.getContext('2d').drawImage(video, 0, 0);
      stream.getVideoTracks()[0].stop();
      div.remove();
      return canvas.toDataURL('image/jpeg', quality);
    }
    ''')
  display(js)
  data = eval_js('takePhoto({})'.format(quality))
  binary = b64decode(data.split(',')[1])
  with open(filename, 'wb') as f:
    f.write(binary)
  return filename

In [ ]:
from IPython.display import Image
try:
  filename = take_photo()
  print('Saved to {}'.format(filename))
  
  # Show the image which was just taken.
  display(Image(filename))
except Exception as err:
  # Errors will be thrown if the user does not have a webcam or if they do not
  # grant the page permission to access it.
  print(str(err))

In [1]:
from ultralyticsplus import YOLO, render_result

def safety_helmet():

    # load model
    model = YOLO('keremberke/yolov8m-hard-hat-detection')

    # set model parameters
    model.overrides['conf'] = 0.25  # NMS confidence threshold
    model.overrides['iou'] = 0.45  # NMS IoU threshold
    model.overrides['agnostic_nms'] = False  # NMS class-agnostic
    model.overrides['max_det'] = 1000  # maximum number of detections per image

# set image
#image = 'https://github.com/RP-SDAAI/Capstone-Project/blob/72573878f2546c1c2984c3e1006ef8e7c72672ec/Helmet-Example01.jpg'

#image = 'https://github.com/ultralytics/yolov5/raw/master/data/images/zidane.jpg'

# perform inference
#results = model.predict(image_path)
    results = model.predict(filename)

#    self.assertEqual(array.shape, (1, 224, 224, 3))

# observe results
    print(results[0].boxes)
    render = render_result(model=model, image=filename, result=results[0])
    render.show()


safety_helmet()


## deploy in actual scenario, i need a device to run the code. (e.g. raspberry pi, nano jetson. laptop)
## run python (*.py) locally for streaming video

ModuleNotFoundError: No module named 'ultralyticsplus'

In [1]:
from ultralyticsplus import YOLO, render_result

def safety_helmet01(frame):

    # load model
    model = YOLO('keremberke/yolov8m-hard-hat-detection')

    # set model parameters
    model.overrides['conf'] = 0.25  # NMS confidence threshold
    model.overrides['iou'] = 0.45  # NMS IoU threshold
    model.overrides['agnostic_nms'] = False  # NMS class-agnostic
    model.overrides['max_det'] = 1000  # maximum number of detections per image

# perform inference
#results = model.predict(image_path)
    results = model.predict(frame)

#    self.assertEqual(array.shape, (1, 224, 224, 3))

# observe results
    print(results[0].boxes)
    render = render_result(model=model, image=frame, result=results[0])
    
    predict_image = model(render)
    im_rgb = cv2.cvtColor(predict_image.imgs[0], cv2.COLOR_BGR2RGB) # Because of OpenCV reading images as BGR
    cv2_imshow(im_rgb)
    
    im_rgb.show()
    #render.show()
    #return render


#safety_helmet()


## deploy in actual scenario, i need a device to run the code. (e.g. raspberry pi, nano jetson. laptop)
## run python (*.py) locally for streaming video

#Need help to get working code for streaming video on google colab

Need to run streaming in local hardware e.g. jupyter notebook

In [ ]:
import cv2

vid = cv2.VideoCapture(0) # For streaming links (#0 : Computer Webcam. Otherwise need to know the RTSP Url of the Webcam, or the IP address that connect directly to the CCTV)
while True:
    rdy,frame = vid.read()
    print(rdy)
    try:
    ##process frame to infer the model
        processframe = safety_helmet01(frame)
    
        cv2.imshow('Video Live IP cam', processframe)
        
        key = cv2.waitKey(1) & 0xFF
        if key ==ord('q'):
            break
    except:
        pass

vid.release()
cv2.destroyAllWindows()

True


Ultralytics YOLOv8.0.43  Python-3.8.13 torch-2.0.0+cpu CPU
Model summary (fused): 218 layers, 25840918 parameters, 0 gradients, 78.7 GFLOPs

0: 480x640 1 NO-Hardhat, 312.8ms
Speed: 0.0ms preprocess, 312.8ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)



tensor([[301.00000, 110.00000, 502.00000, 399.00000,   0.78402,   1.00000]])


0: 480x640 1 NO-Hardhat, 297.5ms
Speed: 0.0ms preprocess, 297.5ms inference, 0.0ms postprocess per image at shape (1, 3, 640, 640)


True


Ultralytics YOLOv8.0.43  Python-3.8.13 torch-2.0.0+cpu CPU
Model summary (fused): 218 layers, 25840918 parameters, 0 gradients, 78.7 GFLOPs

0: 480x640 1 NO-Hardhat, 639.2ms
Speed: 2.6ms preprocess, 639.2ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)



tensor([[300.00000, 110.00000, 500.00000, 399.00000,   0.79659,   1.00000]])


0: 480x640 1 NO-Hardhat, 888.7ms
Speed: 1.9ms preprocess, 888.7ms inference, 0.0ms postprocess per image at shape (1, 3, 640, 640)


True


Ultralytics YOLOv8.0.43  Python-3.8.13 torch-2.0.0+cpu CPU
Model summary (fused): 218 layers, 25840918 parameters, 0 gradients, 78.7 GFLOPs

0: 480x640 1 NO-Hardhat, 461.2ms
Speed: 0.0ms preprocess, 461.2ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)



tensor([[325.00000,  90.00000, 536.00000, 391.00000,   0.78939,   1.00000]])


0: 480x640 1 NO-Hardhat, 461.5ms
Speed: 2.0ms preprocess, 461.5ms inference, 0.0ms postprocess per image at shape (1, 3, 640, 640)


True


Ultralytics YOLOv8.0.43  Python-3.8.13 torch-2.0.0+cpu CPU
Model summary (fused): 218 layers, 25840918 parameters, 0 gradients, 78.7 GFLOPs

0: 480x640 1 NO-Hardhat, 428.8ms
Speed: 1.0ms preprocess, 428.8ms inference, 0.0ms postprocess per image at shape (1, 3, 640, 640)



tensor([[302.00000, 101.00000, 500.00000, 394.00000,   0.75985,   1.00000]])


0: 480x640 1 NO-Hardhat, 461.5ms
Speed: 0.0ms preprocess, 461.5ms inference, 0.0ms postprocess per image at shape (1, 3, 640, 640)


True


Ultralytics YOLOv8.0.43  Python-3.8.13 torch-2.0.0+cpu CPU
Model summary (fused): 218 layers, 25840918 parameters, 0 gradients, 78.7 GFLOPs

0: 480x640 1 NO-Hardhat, 290.8ms
Speed: 1.3ms preprocess, 290.8ms inference, 0.0ms postprocess per image at shape (1, 3, 640, 640)



tensor([[302.00000, 103.00000, 501.00000, 395.00000,   0.75974,   1.00000]])


0: 480x640 1 NO-Hardhat, 309.0ms
Speed: 0.0ms preprocess, 309.0ms inference, 0.0ms postprocess per image at shape (1, 3, 640, 640)


True


Ultralytics YOLOv8.0.43  Python-3.8.13 torch-2.0.0+cpu CPU
Model summary (fused): 218 layers, 25840918 parameters, 0 gradients, 78.7 GFLOPs

0: 480x640 1 NO-Hardhat, 339.9ms
Speed: 3.1ms preprocess, 339.9ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)



tensor([[303.00000, 100.00000, 503.00000, 393.00000,   0.73136,   1.00000]])


0: 480x640 1 NO-Hardhat, 331.3ms
Speed: 2.0ms preprocess, 331.3ms inference, 0.0ms postprocess per image at shape (1, 3, 640, 640)


True


Ultralytics YOLOv8.0.43  Python-3.8.13 torch-2.0.0+cpu CPU
Model summary (fused): 218 layers, 25840918 parameters, 0 gradients, 78.7 GFLOPs

0: 480x640 1 NO-Hardhat, 328.7ms
Speed: 0.0ms preprocess, 328.7ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)



tensor([[303.00000, 104.00000, 503.00000, 397.00000,   0.78032,   1.00000]])


0: 480x640 1 NO-Hardhat, 322.1ms
Speed: 1.0ms preprocess, 322.1ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)


True


Ultralytics YOLOv8.0.43  Python-3.8.13 torch-2.0.0+cpu CPU
Model summary (fused): 218 layers, 25840918 parameters, 0 gradients, 78.7 GFLOPs

0: 480x640 1 NO-Hardhat, 302.2ms
Speed: 0.0ms preprocess, 302.2ms inference, 0.0ms postprocess per image at shape (1, 3, 640, 640)



tensor([[303.00000, 102.00000, 502.00000, 396.00000,   0.76289,   1.00000]])


0: 480x640 1 NO-Hardhat, 300.6ms
Speed: 1.1ms preprocess, 300.6ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)


True


Ultralytics YOLOv8.0.43  Python-3.8.13 torch-2.0.0+cpu CPU
Model summary (fused): 218 layers, 25840918 parameters, 0 gradients, 78.7 GFLOPs

0: 480x640 1 NO-Hardhat, 302.3ms
Speed: 2.0ms preprocess, 302.3ms inference, 0.0ms postprocess per image at shape (1, 3, 640, 640)



tensor([[302.00000, 104.00000, 501.00000, 397.00000,   0.76954,   1.00000]])


0: 480x640 1 NO-Hardhat, 290.1ms
Speed: 0.0ms preprocess, 290.1ms inference, 0.0ms postprocess per image at shape (1, 3, 640, 640)


True


Ultralytics YOLOv8.0.43  Python-3.8.13 torch-2.0.0+cpu CPU
Model summary (fused): 218 layers, 25840918 parameters, 0 gradients, 78.7 GFLOPs

0: 480x640 1 NO-Hardhat, 279.9ms
Speed: 0.0ms preprocess, 279.9ms inference, 0.0ms postprocess per image at shape (1, 3, 640, 640)



tensor([[302.00000, 103.00000, 501.00000, 397.00000,   0.78483,   1.00000]])


0: 480x640 1 NO-Hardhat, 311.4ms
Speed: 0.0ms preprocess, 311.4ms inference, 0.0ms postprocess per image at shape (1, 3, 640, 640)


True


Ultralytics YOLOv8.0.43  Python-3.8.13 torch-2.0.0+cpu CPU
Model summary (fused): 218 layers, 25840918 parameters, 0 gradients, 78.7 GFLOPs

0: 480x640 1 NO-Hardhat, 317.5ms
Speed: 2.0ms preprocess, 317.5ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)



tensor([[302.00000, 104.00000, 501.00000, 396.00000,   0.77295,   1.00000]])


0: 480x640 1 NO-Hardhat, 326.3ms
Speed: 1.0ms preprocess, 326.3ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)


True


Ultralytics YOLOv8.0.43  Python-3.8.13 torch-2.0.0+cpu CPU
Model summary (fused): 218 layers, 25840918 parameters, 0 gradients, 78.7 GFLOPs

0: 480x640 1 NO-Hardhat, 334.3ms
Speed: 0.0ms preprocess, 334.3ms inference, 0.0ms postprocess per image at shape (1, 3, 640, 640)



tensor([[302.00000, 106.00000, 500.00000, 397.00000,   0.76026,   1.00000]])


0: 480x640 1 NO-Hardhat, 318.8ms
Speed: 0.0ms preprocess, 318.8ms inference, 0.0ms postprocess per image at shape (1, 3, 640, 640)


True


Ultralytics YOLOv8.0.43  Python-3.8.13 torch-2.0.0+cpu CPU
Model summary (fused): 218 layers, 25840918 parameters, 0 gradients, 78.7 GFLOPs

0: 480x640 1 NO-Hardhat, 322.2ms
Speed: 0.0ms preprocess, 322.2ms inference, 0.0ms postprocess per image at shape (1, 3, 640, 640)



tensor([[303.00000, 103.00000, 500.00000, 397.00000,   0.76923,   1.00000]])


0: 480x640 1 NO-Hardhat, 320.2ms
Speed: 2.1ms preprocess, 320.2ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)


True


Ultralytics YOLOv8.0.43  Python-3.8.13 torch-2.0.0+cpu CPU
Model summary (fused): 218 layers, 25840918 parameters, 0 gradients, 78.7 GFLOPs

0: 480x640 1 NO-Hardhat, 311.6ms
Speed: 0.0ms preprocess, 311.6ms inference, 0.0ms postprocess per image at shape (1, 3, 640, 640)



tensor([[301.00000, 103.00000, 500.00000, 396.00000,   0.75684,   1.00000]])


0: 480x640 1 NO-Hardhat, 308.5ms
Speed: 1.0ms preprocess, 308.5ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)


True


Ultralytics YOLOv8.0.43  Python-3.8.13 torch-2.0.0+cpu CPU
Model summary (fused): 218 layers, 25840918 parameters, 0 gradients, 78.7 GFLOPs



#Install Gradio for model deployment  
#### Reference: https://github.com/gradio-app/gradio

In [ ]:
!pip install gradio
import gradio as gr

In [ ]:
import gradio as gr  (##running streaming video on gradio will incur charge)

#def test_preprocessing(self):
#        inp = inputs.Webcam(0)
#        array = inp.preprocess(BASE64_IMG)
#        self.assertEqual(array.shape, (1, 224, 224, 3))


##Check with lecturer on the following code ####

#demo = gr.Interface(fn=safety_helmet, inputs="image", outputs="image")

demo = gr.Interface(fn=safety_helmet, inputs=take_photo(), outputs=safety_helmet())

demo.launch(share=True)

In [ ]:
##Sample Gradio code 
#import gradio as gr

#def greet(name):
#    return "Hello " + name + "!"

#demo = gr.Interface(fn=greet, inputs="text", outputs="text")

#fn: the function to wrap a UI around
#inputs: which component(s) to use for the input (e.g. "text", "image" or "audio")
#outputs: which component(s) to use for the output (e.g. "text", "image" or "label")


#demo.launch(share=True)


